# Generated by Django 3.1.7 on 2021-03-13 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(max_length=600)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(blank=True, verbose_name=datetime.date(2021, 3, 13))),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
